### ISSUE TITLE
breaking change between 0.1.7 and 0.1.8/0.1.9

### ISSUE THREAD

**Issue by weemonger** [borisdiakur/memoize-fs#1]
I have a application, which only works with 0.1.7 (or lower) of memoize-fs.
More Information will follow.

**Comment by borisdiakur** [comment]
Please try with 0.1.10 (see https://github.com/borisdiakur/memoize-fs/commit/bd6070fa1b8f2fbff07ba499852f6ffbc9cdc6f4#diff-168726dbe96b3ce427e7fedce31bb0bc)

**Comment by weemonger** [comment]
That did it, thanks.
