### ISSUE TITLE
Changing the body of the memoized function invalidates cache

### ISSUE THREAD

**Issue by polkovnikov-ph** [borisdiakur/memoize-fs#2]
I'm using `memoize-fs` in a crawler to store downloaded files. When the cache of 43k files (2GiB in total) got invalidated, I've found these two rows:

    fnStr = String(fn),
    hash = crypto.createHash('md5').update(fnStr + argsStr + salt).digest('hex');

I think that such behaviour should at least be mentioned in the manual, if not to say that there should be a way to turn it off.

**Comment by borisdiakur** [comment]
Sorry you had an issue. And thanks for collaborating!
memoize-fs@0.2.0 includes the [noBody](https://github.com/borisdiakur/memoize-fs#nobody) option.

**Comment by polkovnikov-ph** [comment]
Thank you!
