### ISSUE TITLE
Make cache file be regular .js file

### ISSUE THREAD

**Issue by tunnckoCore** [borisdiakur/memoize-fs#21]
This will fix most of the "limitations", and also resolve my current problem. 

I'm using it to cache configuration (which may include functions). Basically I memoize the function that loads a config file which returns some configuration that can have functions. 

```js
// tryLoadConfig returns an async function
const loadConfig = tryLoadConfig({
  ...ctxRest,
  testPath,
  config,
  start,
  runnerName,
});
const cfgFunc = await memoize(loadConfig, {
  cacheId: 'load-runner-config',
  astBody: true,
  salt: runnerName
});
const runnerConfig = (await cfgFunc()) || {};
```

In the fresh run, without cache, it writes a cache file with only the non-function things from this configuration object. The thing is that I later getting a function from this config (e.g. `runnerConfig.postHook`) but because on the second run it gets the config from cache it doesn't have the function there.

So. That's clear from the readme. But if we switch the cache files to be regular js file we'll be able to just put there whatever js the memoized function returns.

There's no problem for generating a hash in this way too.

**Comment by tunnckoCore** [comment]
Or, I'm guessing that if we make a simple check if there is `astBody: true` to put function's ast there instead of silently ignore.

**Comment by tunnckoCore** [comment]
Some other thoughts are https://github.com/luin/serialize and https://www.npmjs.com/package/serializr

**Comment by tunnckoCore** [comment]
can confirm that with `node-serialize` everything works :) We should not worry about the "security implications" since we are in the fs and most probably there won't have (end-)user input ability given by the developer anyway.

**Comment by tunnckoCore** [comment]
```diff
- JSON.parse(resultString).data
+ return deserialize(resultString).data
```

and

```diff
const meriyah = require('meriyah')
+ const {serialize, unserialize: deserialize} = require('node-serialize')
```

**Comment by borisdiakur** [comment]
Hey @tunnckoCore, I like the idea of having the ability to use a custom serializer, or choosing one using an option. Maybe could list one as a peer dependency. PRs welcome 😉

**Comment by tunnckoCore** [comment]
Yea, i gone for the options method in my patch too, I'll PR.

Are you okay including `fs-extra` instead of `fs` too? It fixes other problems (including one if you use `fs.mkdir recursive: true` as I suggested) when you have high parallelism (i'm running `memoize-fs` inside jest-runner which runner runs hundreds of files).

**Comment by borisdiakur** [comment]
Yes, I’m ok with using fs-extra.
