### ISSUE TITLE
Timed cache invalidation

### ISSUE THREAD

**Issue by giacecco** [borisdiakur/memoize-fs#3]
Hi @borisdiakur, thanks for your work. Have you thought of adding timed cached invalidation? It would be really useful to stop calling APIs whose results doesn't naturally change that often, particularly if a quota is set, too. Thanks!

**Comment by borisdiakur** [comment]
I guess you mean something like this: https://github.com/medikoo/memoizee#expire-cache-after-given-period-of-time
No, not yet. It shouldn’t be too hard to implement though:

1. Add another option `maxAge`.
2. Call the [`invalidateCache`](https://github.com/borisdiakur/memoize-fs/blob/master/index.js#L206) function after a timeout after [writing the cache](https://github.com/borisdiakur/memoize-fs/blob/master/index.js#L103).
3. Add another test.

If you like, you can give it a shot 😁

**Comment by giacecco** [comment]
I would, but I've never worked with promises in Node, so starting putting my hands into your code is not that obvious. This may be the opportunity to learn... :-)
