### ISSUE TITLE
Option to know if result was cache hit or miss

### ISSUE THREAD

**Issue by vincerubinetti** [borisdiakur/memoize-fs#312]
I could see two ways to do this.

1. Have `onCacheHit`/`onCacheMiss` callback func options. This way we could at least notify our users that a cached value was used/not used. It's probably less useful than option 2, but perhaps there's a clever way a user could write a wrapper function to turn it into 2.
2. Return a cache hit boolean along with the results of the function call, like `const { result, cacheHit } = memoizedFunc();`. Not sure how you'd want to implement the API there. Maybe a `withCacheHit` option that changes the return signature into that instead of just `const result = memoizedFunc()`.

**Comment by borisdiakur** [comment]
Hey @vincerubinetti 👋🏻,
thanks for writing up the issue. The feature is implemented and published with v4.1.1 📦🚀
See https://github.com/borisdiakur/memoize-fs?tab=readme-ov-file#checking-for-a-cache-hit
