### ISSUE TITLE
{ force: true } only works once.

### ISSUE THREAD

**Issue by gburtini** [borisdiakur/memoize-fs#32]
I have fixed it by removing line 249 in my own branch, but I'm not sure what the intent of this was, so I haven't suggested a PR.

https://github.com/borisdiakur/memoize-fs/blob/6f4e785219bf9eb007f9721a4396a9994d65f7e4/index.js#L249

So, as a pseudo-example:

```js
let callCount = 0;
const f = (_) => {
  callCount++;
}

const example = async () => {
  const memoizedF = await memoizer.fn(f, { force: true });
  
  // two calls.
  memoizedF(); 
  memoizedF();
}

example(); // call count is 1.
example(); // call count is 2.
```

This behavior gets weirder when you consider how it plays with argument level caching: **only the first call after creating the memoizedF seems to have its cache renewed,** that is, in the following code:

```js
const memoizedF = await memoizer.fn(f);
memoizedF();
memoizedF(2);

const forceMemoizedF = await memoizer.fn(f, { force: true });
forceMemoizedF(); 
forceMemoizedF(2); // this will not have cache renewed.
```

As far as I can tell, removing line 249 fixes this with no side effects, but I haven't run your tests or otherwise figured out why you may wish for this run-once type behavior.

**Comment by borisdiakur** [comment]
It's a one time thing, because it doesn't make sense to have a memoised function that actually is not caching anything. The idea is: If you need a specific function that has previously been cached with specific args to be re-cached, you simply memoise it again with the force option and after that it behaves as previously, using existing cache. If you need to invalidate all cache for a function, you can use [cache invalidation](https://github.com/borisdiakur/memoize-fs#manual-cache-invalidation). Hope this explains it well enough. Guess I should add this explanation to the README, what do you think?

**Comment by gburtini** [comment]
OK, makes sense. I'm not sure I understand the use case, as I don't think the typical implementation won't have multiple calls to `memoizer.fn` for the same function, but I can make it work as described. 

For my use case, I was hoping to allow a user to trigger invalidations selectively. I will rebuild around the `{ force: true }` functionality as you describe, instead of exporting a (singular) memoized function from a module.

In case you're curious, I'll describe a stylized version of my envisioned use case below, but I agree there's nothing to do with this issue except perhaps update the documentation.

```
long-running.js

module.exports = (opts) => memoizer.fn(f, opts);
```

```
user.js

const memoizedF = require("./long-running")({ 
  force: process.argv[1] === "reset" 
}); // or some other mechanism for a user to explicitly rebuild the cache for the calls about to be made.

// assorted, potentially multiple calls to memoizedF.
memoizedF(process.argv[2]);
memoizedF("hello-world");
```

Thanks for the great library. It made my own project 10x more useful with only 10 minutes initial integration work. :+1:
