### ISSUE TITLE
Promisified function that also accepts callback

### ISSUE THREAD

**Issue by laggingreflex** [borisdiakur/memoize-fs#4]
Awesome tool first of all!

I have an unusual case that I have a promisified function (returns a promise) but also takes a callback (although it's for a different purpose). This makes it incorrectly identify it as an async function. 

As a workaround for now I'm just passing an extra non-function last argument, but it'd be better if this could be set manually like in options `{promisified}`, or if it were in the API like `memoize.async`/promisified.

**Comment by borisdiakur** [comment]
Thanks!

The case you describe sounds like an anti-pattern to me (side-effects... callback may not be called in case of an exception...). Maybe you should rethink and refactor your code? Also I think your workaround (for now) is acceptable in this case. Just make sure the last parameter is verbose (so other developers understand its purpose), something like `'needed_for_correct_memoization'`.
