### ISSUE TITLE
Serialize function AST instead of source

### ISSUE THREAD

**Issue by josephfrazier** [borisdiakur/memoize-fs#6]
Hey @borisdiakur, thanks for the module! I was wondering if you'd be willing to accept a patch that would allow the comments/formatting of a function to change, without invalidating the cache. The idea is that instead of [hashing the source code of the function](https://github.com/borisdiakur/memoize-fs/blob/358c085aa51684b880a788eb6270698b485c93aa/index.js#L52), we would use a parser like [babylon](https://github.com/babel/babylon) to build an AST (abstract syntax tree) of the function that represents its semantic behavior while disregarding comments/formatting/etc. The AST would be serialized into JSON and then included in the hash.

**Comment by borisdiakur** [comment]
Hi @josephfrazier. Sure. Creating the syntax tree itself may be expansive and changing the current behaviour would require a major version bump. So you’d probably make it an option and call it `'ast'` or what ever.

**Comment by josephfrazier** [comment]
Great, I'll see what I can come up with. I agree that it should be an option.

Note to self: Ideally, this would eventually be resistant to variable renaming within the function, but that would require a more sophisticated analysis (using something like http://esprima.org/demo/rename.html).

**Comment by borisdiakur** [comment]
Thanks @josephfrazier!

**Comment by josephfrazier** [comment]
Thanks for the quick merge/release! How would you feel about the `astBody` feature automatically looking for cached file paths generated without `astBody` set, and migrating them to their new location? This would make it easier to start using `astBody` without busting pre-existing caches.

**Comment by borisdiakur** [comment]
My gut tells me that migration tasks should be avoided in production code. They should rather be implemented in a deployment pipeline.

**Comment by josephfrazier** [comment]
That makes sense. In order for such a migration to be possible, I think we should export `getCacheFilePath` . What do you think?

**Comment by borisdiakur** [comment]
Yes, that sounds reasonable.
